version: "3.1"

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $PG_PASS
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./pgdata:/var/lib/postgresql
    env_file:
      - ".env"

  tgbot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
      - .:/src


networks:
  botnet:
    driver: bridge